# Makefile generated by create_makefile.sh

default : all.vo

clean :
	rm -f syntax/.*.aux       syntax/*.glob       syntax/*.vo
	rm -f semantics/.*.aux    semantics/*.glob    semantics/*.vo
	rm -f substitution/.*.aux substitution/*.glob substitution/*.vo
	rm -f axioms/.*.aux       axioms/*.glob       axioms/*.vo
	rm -f checker/.*.aux      checker/*.glob      checker/*.vo
	rm -f examples/.*.aux     examples/*.glob     examples/*.vo
	rm -f coq-tools/.*.aux    coq-tools/*.glob    coq-tools/*.vo

syntax/symbol.vo : syntax/symbol.v
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples syntax/symbol.v

semantics/semantics_util.vo : semantics/semantics_util.v syntax/list_util.vo syntax/vec_util.vo syntax/reals_util.vo syntax/symbol_lemmas.vo semantics/deriv_util.vo syntax/state.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples semantics/semantics_util.v

semantics/coincidence.vo : semantics/coincidence.v semantics/static_sem_lemmas.vo semantics/ext_interpretation.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples semantics/coincidence.v

syntax/tactics_util.vo : syntax/tactics_util.v coq-tools/tactics2.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples syntax/tactics_util.v

coq-tools/tactics2.vo : coq-tools/tactics2.v coq-tools/UsefulTypes.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples coq-tools/tactics2.v

all.vo : all.v examples/example1.vo examples/example2.vo examples/DI_and.vo examples/DI_or.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples all.v

semantics/bound_effect.vo : semantics/bound_effect.v semantics/static_sem_lemmas.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples semantics/bound_effect.v

syntax/vec_util.vo : syntax/vec_util.v syntax/tactics_util.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples syntax/vec_util.v

examples/example1.vo : examples/example1.v checker/checker.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples examples/example1.v

semantics/eassignables.vo : semantics/eassignables.v semantics/fcset.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples semantics/eassignables.v

examples/example2.vo : examples/example2.v checker/checker.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples examples/example2.v

coq-tools/LibTactics.vo : coq-tools/LibTactics.v
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples coq-tools/LibTactics.v

coq-tools/eq_rel.vo : coq-tools/eq_rel.v coq-tools/universe.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples coq-tools/eq_rel.v

semantics/fcset.vo : semantics/fcset.v syntax/symbol_lemmas.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples semantics/fcset.v

substitution/adjoint_interpretation.vo : substitution/adjoint_interpretation.v substitution/US.vo substitution/US_defs.vo semantics/static_sem_lemmas.vo substitution/lookup_lemmas.vo substitution/admissible_terms.vo substitution/eassignables_terms.vo substitution/lookup_lemmas.vo syntax/list_util.vo semantics/coincidence.vo semantics/bound_effect.vo semantics/dynamic_semantics_prop.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples substitution/adjoint_interpretation.v

semantics/static_sem.vo : semantics/static_sem.v syntax/terms_util.vo semantics/semantics_util.vo semantics/fcset.vo semantics/eassignables.vo semantics/free_vars_term.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples semantics/static_sem.v

coq-tools/universe.vo : coq-tools/universe.v
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples coq-tools/universe.v

syntax/terms_util.vo : syntax/terms_util.v syntax/expressions.vo syntax/symbol_lemmas.vo syntax/vec_util.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples syntax/terms_util.v

semantics/deriv_util.vo : semantics/deriv_util.v syntax/tactics_util.vo syntax/reals_util.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples semantics/deriv_util.v

semantics/ext_interpretation.vo : semantics/ext_interpretation.v semantics/static_sem.vo semantics/dynamic_semantics.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples semantics/ext_interpretation.v

examples/DI_or.vo : examples/DI_or.v checker/checker.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples examples/DI_or.v

examples/DI_and.vo : examples/DI_and.v checker/checker.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples examples/DI_and.v

semantics/free_vars_term.vo : semantics/free_vars_term.v syntax/terms_util.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples semantics/free_vars_term.v

coq-tools/UsefulTypes.vo : coq-tools/UsefulTypes.v coq-tools/tactics.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples coq-tools/UsefulTypes.v

syntax/reals_util.vo : syntax/reals_util.v coq-tools/tactics2.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples syntax/reals_util.v

substitution/lookup_lemmas.vo : substitution/lookup_lemmas.v semantics/static_sem_lemmas.vo substitution/US.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples substitution/lookup_lemmas.v

substitution/swapping.vo : substitution/swapping.v substitution/soundness.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples substitution/swapping.v

syntax/terms_util2.vo : syntax/terms_util2.v syntax/terms_util.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples syntax/terms_util2.v

axioms/integral.vo : axioms/integral.v syntax/reals_util.vo semantics/deriv_util.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples axioms/integral.v

substitution/eassignables_subterm.vo : substitution/eassignables_subterm.v semantics/static_sem_lemmas.vo substitution/US.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples substitution/eassignables_subterm.v

semantics/dynamic_semantics_prop.vo : semantics/dynamic_semantics_prop.v semantics/dynamic_semantics.vo semantics/semantics_util.vo syntax/terms_util2.vo syntax/list_util.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples semantics/dynamic_semantics_prop.v

substitution/US.vo : substitution/US.v semantics/static_sem.vo coq-tools/tactics2.vo syntax/terms_util2.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples substitution/US.v

axioms/differential_axioms.vo : axioms/differential_axioms.v substitution/soundness.vo axioms/integral.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples axioms/differential_axioms.v

axioms/DDLaxioms.vo : axioms/DDLaxioms.v substitution/soundness.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples axioms/DDLaxioms.v

semantics/static_sem_lemmas.vo : semantics/static_sem_lemmas.v semantics/static_sem.vo semantics/dynamic_semantics.vo syntax/terms_util2.vo syntax/list_util.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples semantics/static_sem_lemmas.v

syntax/expressions.vo : syntax/expressions.v syntax/symbol.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples syntax/expressions.v

substitution/US_lemmas.vo : substitution/US_lemmas.v substitution/adjoint_interpretation.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples substitution/US_lemmas.v

axioms/differential.vo : axioms/differential.v substitution/US_lemmas.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples axioms/differential.v

syntax/decidability.vo : syntax/decidability.v syntax/terms_util2.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples syntax/decidability.v

syntax/list_util.vo : syntax/list_util.v coq-tools/tactics2.vo syntax/tactics_util.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples syntax/list_util.v

semantics/dynamic_semantics.vo : semantics/dynamic_semantics.v syntax/expressions.vo semantics/semantics_util.vo syntax/terms_util.vo semantics/deriv_util.vo syntax/state.vo semantics/free_vars_term.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples semantics/dynamic_semantics.v

syntax/symbol_lemmas.vo : syntax/symbol_lemmas.v syntax/symbol.vo syntax/list_util.vo syntax/tactics_util.vo syntax/reals_util.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples syntax/symbol_lemmas.v

substitution/admissible_terms.vo : substitution/admissible_terms.v substitution/eassignables_subterm.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples substitution/admissible_terms.v

substitution/eassignables_terms.vo : substitution/eassignables_terms.v substitution/eassignables_subterm.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples substitution/eassignables_terms.v

axioms/differential_invariant.vo : axioms/differential_invariant.v substitution/soundness.vo axioms/differential.vo axioms/integral.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples axioms/differential_invariant.v

substitution/soundness.vo : substitution/soundness.v substitution/US_lemmas.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples substitution/soundness.v

coq-tools/tactics.vo : coq-tools/tactics.v coq-tools/eq_rel.vo coq-tools/LibTactics.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples coq-tools/tactics.v

syntax/state.vo : syntax/state.v syntax/symbol_lemmas.vo syntax/tactics_util.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples syntax/state.v

checker/checker.vo : checker/checker.v substitution/soundness.vo substitution/swapping.vo axioms/DDLaxioms.vo axioms/differential_axioms.vo axioms/differential_invariant.vo syntax/decidability.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples checker/checker.v

substitution/US_defs.vo : substitution/US_defs.v substitution/US.vo
	coqc -R coq-tools util -R syntax syntax -R semantics semantics -R substitution substitution -R axioms axioms -R checker checker -R examples examples substitution/US_defs.v
